version: 2

jobs:
  lint:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: npm ci --unsafe-perm
      - run: npm run lint
  test:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: npm ci --unsafe-perm
      - run: npm run test
  build:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: npm ci --unsafe-perm
      - run: npm run build
      - run: npm run verify
      - persist_to_workspace:
          root: ./
          paths:
            - dist/
  deploy:
    docker:
      - image: mesosphere/aws-cli
    steps:
      - attach_workspace:
          at: ./
      - run: tar -zcvf lambda.tar.gz dist/
      - run: aws cloudformation deploy

workflows:
  version: 2
  default:
    jobs:
      - lint
      - test
      - build
      - deploy:
          requires:
            - lint
            - test
            - build
          filters:
            branches:
              only:
                - master
